from PyQt5 import QtCore, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(211, 184)
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.eq_1 = QtWidgets.QLabel(Form)
        self.eq_1.setObjectName("eq_1")
        self.gridLayout.addWidget(self.eq_1, 1, 0, 1, 1)
        self.input_second_number = QtWidgets.QLineEdit(Form)
        self.input_second_number.setObjectName("input_second_number")
        self.gridLayout.addWidget(self.input_second_number, 2, 3, 1, 1, QtCore.Qt.AlignHCenter)
        self.first_number = QtWidgets.QLabel(Form)
        self.first_number.setObjectName("first_number")
        self.gridLayout.addWidget(self.first_number, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.second_number = QtWidgets.QLabel(Form)
        self.second_number.setObjectName("second_number")
        self.gridLayout.addWidget(self.second_number, 2, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.input_first_number = QtWidgets.QLineEdit(Form)
        self.input_first_number.setObjectName("input_first_number")
        self.gridLayout.addWidget(self.input_first_number, 0, 3, 1, 1, QtCore.Qt.AlignHCenter)
        self.ravno = QtWidgets.QLabel(Form)
        self.ravno.setObjectName("ravno")
        self.gridLayout.addWidget(self.ravno, 0, 1, 3, 1, QtCore.Qt.AlignHCenter)
        self.input_number = QtWidgets.QLineEdit(Form)
        self.input_number.setObjectName("input_number")
        self.gridLayout.addWidget(self.input_number, 0, 2, 3, 1, QtCore.Qt.AlignHCenter)
        self.eq_2 = QtWidgets.QLabel(Form)
        self.eq_2.setObjectName("eq_2")
        self.gridLayout.addWidget(self.eq_2, 1, 3, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.continue_2 = QtWidgets.QPushButton(Form)
        self.continue_2.setObjectName("continue_2")
        self.gridLayout_2.addWidget(self.continue_2, 2, 0, 1, 1)
        self.check = QtWidgets.QPushButton(Form)
        self.check.setObjectName("check")
        self.gridLayout_2.addWidget(self.check, 1, 0, 1, 1)
        self.otvet = QtWidgets.QLabel(Form)
        self.otvet.setText("")
        self.otvet.setObjectName("otvet")
        self.gridLayout_2.addWidget(self.otvet, 3, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.eq_1.setText(_translate("Form", "———"))
        self.first_number.setText(_translate("Form", "1"))
        self.second_number.setText(_translate("Form", "3"))
        self.ravno.setText(_translate("Form", "="))
        self.eq_2.setText(_translate("Form", "————"))
        self.continue_2.setText(_translate("Form", "Продолжить дальше"))
        self.check.setText(_translate("Form", "Проверить"))
