from PyQt5 import QtCore, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(509, 215)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.fourth_number = QtWidgets.QLabel(Form)
        self.fourth_number.setText("")
        self.fourth_number.setObjectName("fourth_number")
        self.gridLayout.addWidget(self.fourth_number, 0, 2, 1, 1)
        self.input_second_number = QtWidgets.QLineEdit(Form)
        self.input_second_number.setObjectName("input_second_number")
        self.gridLayout.addWidget(self.input_second_number, 2, 4, 1, 1)
        self.input_first_number = QtWidgets.QLineEdit(Form)
        self.input_first_number.setObjectName("input_first_number")
        self.gridLayout.addWidget(self.input_first_number, 0, 4, 1, 1)
        self.check = QtWidgets.QPushButton(Form)
        self.check.setObjectName("check")
        self.gridLayout.addWidget(self.check, 3, 0, 1, 5)
        self.eq_3 = QtWidgets.QLabel(Form)
        self.eq_3.setObjectName("eq_3")
        self.gridLayout.addWidget(self.eq_3, 1, 4, 1, 1)
        self.continue_2 = QtWidgets.QPushButton(Form)
        self.continue_2.setObjectName("continue_2")
        self.gridLayout.addWidget(self.continue_2, 4, 0, 1, 5)
        self.second_number = QtWidgets.QLabel(Form)
        self.second_number.setText("")
        self.second_number.setObjectName("second_number")
        self.gridLayout.addWidget(self.second_number, 2, 0, 1, 1)
        self.ravno = QtWidgets.QLabel(Form)
        self.ravno.setObjectName("ravno")
        self.gridLayout.addWidget(self.ravno, 1, 3, 1, 1)
        self.eq_1 = QtWidgets.QLabel(Form)
        self.eq_1.setObjectName("eq_1")
        self.gridLayout.addWidget(self.eq_1, 1, 0, 1, 1)
        self.sign = QtWidgets.QLabel(Form)
        self.sign.setObjectName("sign")
        self.gridLayout.addWidget(self.sign, 1, 1, 1, 1)
        self.first_number = QtWidgets.QLabel(Form)
        self.first_number.setText("")
        self.first_number.setObjectName("first_number")
        self.gridLayout.addWidget(self.first_number, 0, 0, 1, 1)
        self.firth_number = QtWidgets.QLabel(Form)
        self.firth_number.setText("")
        self.firth_number.setObjectName("firth_number")
        self.gridLayout.addWidget(self.firth_number, 2, 2, 1, 1)
        self.eq_2 = QtWidgets.QLabel(Form)
        self.eq_2.setObjectName("eq_2")
        self.gridLayout.addWidget(self.eq_2, 1, 2, 1, 1)
        self.skip = QtWidgets.QPushButton(Form)
        self.skip.setObjectName("skip")
        self.gridLayout.addWidget(self.skip, 5, 0, 1, 5)
        self.otvet = QtWidgets.QLabel(Form)
        self.otvet.setText("")
        self.otvet.setObjectName("otvet")
        self.gridLayout.addWidget(self.otvet, 6, 0, 1, 5)
        self.verticalLayout_2.addLayout(self.gridLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.check.setText(_translate("Form", "Проверить"))
        self.eq_3.setText(_translate("Form", "———————————"))
        self.continue_2.setText(_translate("Form", "Продолжить дальше"))
        self.ravno.setText(_translate("Form", "="))
        self.eq_1.setText(_translate("Form", "——————————"))
        self.sign.setText(_translate("Form", "-"))
        self.eq_2.setText(_translate("Form", "——————————"))
        self.skip.setText(_translate("Form", "Пропустить задание"))
